### ISSUE TITLE
Plans for a Downloadable Tool?

### ISSUE THREAD

**Issue by SkyeRangerDelta** [hpeinar/stardewplanner#19]
Hey man, just wanna say, this is a fantastic tool and I applaud you for your time and effort.

Now, what I would like to know is if you plan to release a downloadable version of it. I love SV, but I don't have a constant 24/7 internet connection. If there was an offline/downloadable version of this tool, you would be the best developer in the flippin' world to me.

I don't want to cause a disruption, just want to know if you can do that for me/plan to do it.

Thanks,
-Skye

**Comment by hpeinar** [comment]
Hi!

Downloadable tool is indeed planned for both Windows and OS X which will also work offline.
I'm trying my best to release this as soon as possible (read: could happen this week).

**Comment by SkyeRangerDelta** [comment]
Wow! Thanks!

**Comment by hpeinar** [comment]
I've released beta version of the offline planner.

Please note that:
- It is currently not possible to load online plans in the app or save them online.
- It currently supports only one saved plan (it'll be automatically loaded when you boot the app up next time but be sure to save it!).
- As this is beta release, there might be problems with it
- This app is meant for offline use (or for those with very slow internet connection). If you have internet access, please keep using the online planner.
- It is not possible to import your save game file to the app right now.

You can find the downloadables here:
Windows: https://github.com/hpeinar/stardewplanner/raw/electron/dist/StardewValleyPlanner-win.zip
OS X: https://github.com/hpeinar/stardewplanner/raw/electron/dist/StardewValleyPlanner-osx.tar.gz
Linux: https://github.com/hpeinar/stardewplanner/raw/electron/dist/StardewValleyPlanner-linux.tar.gz

If you have any problems or issues with it, report them here or directly to my email. Please include what OS and what version of the OS are you running. (ex: Windows 10 latest).

**Comment by SkyeRangerDelta** [comment]
Appreciate it mate, I run Windows 7 Home on an Apple iMac.
Hopefully this offline one will run a little better than that of inside my browser. Seems to lag for me.

**Comment by hpeinar** [comment]
I wouldn't bet on it to have better performance because essentially it is the same as running it in the browser. The package contains Chromium and has the same planner code as online version.

Let me know though.

**Comment by SkyeRangerDelta** [comment]
Oh, it definitely runs better offline. My internet plan gives me about 8.3MB/s so that shouldn't be the trouble. It's got to be something inside my browser that makes it lag (Firefox). Anyways, this offline tool is beautiful;

Thanks again mate!
