### ISSUE TITLE
Main planner site gives Internal Server Error.

### ISSUE THREAD

**Issue by SephirothWS** [hpeinar/stardewplanner#22]
Can't actually use the planner currently, it gives off an Internal Server Error over at https://stardew.info/planner/

**Comment by hpeinar** [comment]
Dam.

I cant have a look before few hours.

Thanks for reporting though.

**Comment by hpeinar** [comment]
Actually got it fixed via phone.

With best,
Henrik

**Comment by SephirothWS** [comment]
Excellent. Thank you sir. :)
