### ISSUE TITLE
Bug(?) with passing to upload.farm for rendering and rate limiter

### ISSUE THREAD

**Issue by Laukei** [hpeinar/stardewplanner#26]
Hi Henrik, I hope things are well!

I got an email from someone today who has a problem with how upload.farm handles his save. The bug involved is relatively simple to fix, but he also mentioned that

> On the planner, when trying to render w/ a different season, I receive
this error:
> 
> stardew.info say: Rendering failed. Please try again in few minutes

I loaded his savefile into the planner and rendered it in a couple of different seasons, which worked fine, so I tried to figure out what the bug could be he was getting. The only thing I can think is that he might be hitting the upload.farm plan rendering API rate limiter. **If a render hits the rate limiter, does it have a separate alert to the user, or does it just time out and say rendering failed?** If it does this, would it be possible to give a different error when it times out, maybe mentioning that upload.farm is rate limiting and to try again later? (I hope that's not too demanding, apologies if it is...)

Cheers!
Rob

**Comment by hpeinar** [comment]
I've added separate error message when upload.farm API responds with status code 429 (rate limited).
