### ISSUE TITLE
download cannot run

### ISSUE THREAD

**Issue by hantieyi** [hpeinar/stardewplanner#32]
Hello！ヽ(･ω･´ﾒ)
I installed MySQL，Create a database planner，Function db_init.sql  Create a table farm。but report errors:
ER_ACCESS_DENIED_ERROR errno 1054 sqlMessage Unknown colum 'layout' in field list .
Cannot run 。

**Comment by hantieyi** [comment]
click save current plan  error ╮(╯﹏╰）╭

**Comment by antomarsi** [comment]
i Think that the username and password that you used is invalid. Can you check if the password to your database is the same as the MySql Server that you installed?

**Comment by hpeinar** [comment]
Closing as old issue.
