### ISSUE TITLE
3rd dimension: Time

### ISSUE THREAD

**Issue by saraid** [hpeinar/stardewplanner#35]
Hello,

I recently decided that I needed an easy way to plan my Stardew Valley farm's harvest across an entire season, so I threw something together in my preferred language of choice, Ruby. This was successful, so I wrapped it inside an API and tossed it onto a free plan on Heroku.

Here's the code, which is MIT-licensed, so you can do whatever with it.

https://github.com/saraid/stardew_calendar

I have no idea whether or not my tool can be integrated into your planner, but it would be nice to. Feel free to request features or make pull requests or fork and do your own thing. Also feel free to hit the Heroku instance I put up, but I don't really know anything about how Heroku will rate-limit me, and free plans don't get metrics, so I won't have any idea what's going on.

**Comment by hpeinar** [comment]
Interesting API. It could definitely be integrated to the planner, but I lack the time to do so as this would be a considerable undertaking. It would require a lot of new logic and UI to handle the "time".

So I'm closing the issue for now.
