### ISSUE TITLE
Can't move buildings after update

### ISSUE THREAD

**Issue by jjnilton** [hpeinar/stardewplanner#40]
Noticed that there was a upgrade today, now it seems that move buildings don't work anymore, they just fade out when you click them.

**Comment by hpeinar** [comment]
Thanks for reporting this. I'll look into it.

**Comment by hpeinar** [comment]
Should be fixed now. Refresh to get the changes as always.

**Comment by jjnilton** [comment]
Seems to be ok now, thanks!
