### ISSUE TITLE
Game patched

### ISSUE THREAD

**Issue by darylknight** [hpeinar/stardewplanner#6]
Hiya, you can't build the stable in the top right hand corner of the map any more, thought you might want to update the planner :)

**Comment by mharrington622** [comment]
I've noticed that the game has separate placement rules for buildings and "normal objects" (furnace, kegs, etc...) that the planner doesn't take into account.  For example, you cannot place buildings from Robin flush against the right side of the map or on any grass tiles.  So the planner could do with some updating to follow these rules in general.  There's probably some kind of layering concept that can be taken advantage of for this e.g. Dirt < Grass < Roads & Paths < Equipment.

**Comment by hpeinar** [comment]
There problems would be solved with more boundaries layers, discussed in: https://github.com/hpeinar/stardewplanner/issues/7
