### ISSUE TITLE
Ads Cover Half the Planner

### ISSUE THREAD

**Issue by RogueRedHawk** [hpeinar/stardewplanner#73]
![image](https://user-images.githubusercontent.com/57609258/213901321-8fa07350-606a-4909-892d-01ea3a7d7166.png)

The ads on this page take up the entire left side of the planner. I don't mind having ads, but they shouldn't obstruct half the page. Maybe a banner ad would be fine but I'm unable to use the site, I cannot even close the ads. Please fix this, because this site looks very useful otherwise.

**Comment by RogueRedHawk** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57609258/213901379-2cadd454-8a1b-4e3c-83c7-7ce663b39fb0.png">

Here's another picture showing in another browser, Edge, the same issue.

**Comment by hpeinar** [comment]
@RogueRedHawk thank you very much for the report
I'm changing the ad provider in upcoming days so please hang tight.

I'll update the issue once the new provider is live.

**Comment by hpeinar** [comment]
I've deployed the new ads to live, let me know if you are encountering any of the similar issues.

**Comment by RogueRedHawk** [comment]
Great! This is exactly what I had in mind, there's a banner ad across the bottom that does not cover any of the editor elements. Thank you so much!
