### ISSUE TITLE
Suggestion: Moving the greenhouse

### ISSUE THREAD

**Issue by yvvt0379** [hpeinar/stardewplanner#81]
When I finish the community center, the greenhouse becomes movable. However, there seems no way to move the greenhouse in the planner.

**Comment by FluffyPunk** [comment]
Same story for shipping bin, except one moment - that's for start all the way

**Comment by hpeinar** [comment]
Please try out the new version instead, where greenhouse is movable (at least on official maps) and shipping bin freely placeable :)

https://v3.stardew.info/planner

Closing this issue as this problem will not be fixed in the v2 (which is the current live one).
