### ISSUE TITLE
Please consider adding the medow farm

### ISSUE THREAD

**Issue by PookieChu** [hpeinar/stardewplanner#84]
I've noticed both the V2 and V3 beta don't have the meadow farm layout which is what I personally use on PC and it would be appreciated if this map could be included for those of us who use it.

**Comment by KeremKaratas** [comment]
Isn't ranching farm meadow layout?

**Comment by hpeinar** [comment]
Ranching is indeed available on both versions of the planners :)

<img width="217" alt="Screenshot 2024-04-18 at 23 27 32" src="https://github.com/hpeinar/stardewplanner/assets/490959/132e2df4-f5e4-4bdd-960c-3787b7cc143e">
